-- 코드를 입력하세요
SELECT A.WRITER_ID,B.NICKNAME,SUM(PRICE) as TOTAL_SALES
from USED_GOODS_BOARD as A join USED_GOODS_USER as B on A.WRITER_ID = B.USER_ID
where STATUS = 'DONE'
group by USER_ID
having SUM(PRICE)>=700000
order by TOTAL_SALES
