-- 코드를 입력하세요
SELECT A.CATEGORY, SUM(B.SALES) as TOTAL_SALES
from BOOK as A join BOOK_SALES as B on A.BOOK_ID = B.BOOK_ID
where YEAR(B.SALES_DATE)=2022 and MONTH(B.SALES_DATE)=01
group by A.CATEGORY
order by A.CATEGORY